#!/usr/bin/env python3
"""
Create a GitHub Issue with suggested new AI safety opportunities.

Reads suggested_additions.json and creates a GitHub Issue using the `gh` CLI.

Usage:
    python create_issue.py
    python create_issue.py --dry-run   # Just print the issue, don't create it
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from typing import Dict, List


def load_suggestions(path: str = "suggested_additions.json") -> Dict:
    """Load the suggested additions file."""
    with open(path, "r") as f:
        return json.load(f)


def build_issue_body(suggestions: List[Dict]) -> str:
    """Build the markdown body of the GitHub Issue."""
    # Group by category
    by_category = {}  # type: Dict[str, List[Dict]]
    for s in suggestions:
        cat = s.get("category", "unknown")
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append(s)

    category_labels = {
        "fellowships": "Fellowships",
        "grants": "Grants & Funding",
        "tech-internships": "Technical Internships",
        "policy-internships": "Policy Internships",
        "jobs": "Jobs",
        "community": "Community & Resources",
        "orgs-to-watch": "Organizations to Watch",
        "phd": "PhD & Academic",
        "startups": "Startups & Incubators",
        "career-resources": "Career Resources",
        "unknown": "Uncategorized",
    }

    lines = []
    lines.append("The automated scanner found the following new AI safety opportunities ")
    lines.append("that are **not currently tracked** in `resources.json`.\n")
    lines.append("Please review each suggestion and add relevant ones to the site.\n")
    lines.append("---\n")

    for cat, items in sorted(by_category.items()):
        label = category_labels.get(cat, cat.replace("-", " ").title())
        lines.append("## {}\n".format(label))

        for item in items:
            score = item.get("relevance_score", "?")
            name = item.get("name", "Unknown")
            url = item.get("url", "")
            desc = item.get("description", "No description available")
            status = item.get("status", "unknown")
            deadline = item.get("deadline")

            lines.append("### [{}]({})".format(name, url))
            lines.append("- **Relevance:** {}/5".format(score))
            lines.append("- **Category:** {}".format(label))
            lines.append("- **Status:** {}".format(status))
            if deadline:
                lines.append("- **Deadline:** {}".format(deadline))
            lines.append("- **Description:** {}".format(desc))
            lines.append("")

    lines.append("---\n")
    lines.append("*This issue was automatically generated by the discovery scanner.*")
    lines.append("")
    lines.append("<details><summary>How to add these</summary>\n")
    lines.append("For each opportunity you want to add:")
    lines.append("1. Verify the URL is correct and the opportunity is active")
    lines.append("2. Add an entry to `resources.json` with the appropriate fields")
    lines.append("3. Run the updater to populate status details")
    lines.append("</details>")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Create GitHub Issue with scan results")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the issue instead of creating it",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    suggestions_path = os.path.join(script_dir, "suggested_additions.json")

    if not os.path.exists(suggestions_path):
        print("No suggested_additions.json found. Run scanner.py first.")
        sys.exit(0)

    data = load_suggestions(suggestions_path)
    suggestions = data.get("suggestions", [])

    if not suggestions:
        print("No new suggestions found. Nothing to report.")
        sys.exit(0)

    count = len(suggestions)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = "Scanner: {} new AI safety opportunities found ({})".format(count, today)
    body = build_issue_body(suggestions)

    if args.dry_run:
        print("=" * 60)
        print("TITLE: {}".format(title))
        print("=" * 60)
        print(body)
        print("=" * 60)
        print("[DRY RUN] Issue not created.")
        return

    # Create the issue using gh CLI
    try:
        result = subprocess.run(
            [
                "gh", "issue", "create",
                "--title", title,
                "--body", body,
                "--label", "scanner",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        print("Issue created: {}".format(result.stdout.strip()))
    except FileNotFoundError:
        print("ERROR: `gh` CLI not found. Install it: https://cli.github.com/")
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        # Try without label in case it doesn't exist
        print("Note: Could not create with label, trying without...")
        try:
            result = subprocess.run(
                [
                    "gh", "issue", "create",
                    "--title", title,
                    "--body", body,
                ],
                capture_output=True,
                text=True,
                check=True,
            )
            print("Issue created: {}".format(result.stdout.strip()))
        except subprocess.CalledProcessError as e2:
            print("ERROR creating issue: {}".format(e2.stderr))
            sys.exit(1)


if __name__ == "__main__":
    main()
